#state : 27(ver.)
Header header
float64 Measure_Rel_Pos_Y
float64 Measure_Rel_Pos_X 
float64 Width
float64 Length
float64 Heading_Angle
float64 Fused_FVT_ID
float64 Fused_FRT_ID
float64 ABS_Vel
float64 Motion
float64 Shape
float64 Tracking_Rel_Pos_Y
float64 Tracking_Rel_Pos_X
float64 Tracking_Rel_Vel_Y
float64 Tracking_Rel_Vel_X
float64 Updated_Age
float64 Coasting_Age
float64 Life_Time
float64 Rel_Pos_Normal
float64 Vehicle_Recognition_ID
float64 Vehicle_Recognition
float64 Pedestrian_Recognition_ID
float64 Pedestrian_Recognition
float64 Cyclist_Recognition_ID
float64 Cyclist_Recognition
float64 EScooter_Recognition_ID
float64 EScooter_Recognition




